### PR TITLE
Added VIA Parser for bboxes. Issue #573.

### PR DESCRIPTION
**Pull request by jerbly**
VIABBoxParser parses JSON annotations from the VGG Image Annotator V2.
    See (https://www.robots.ox.ac.uk/~vgg/software/via/)

    Just `polygon` and `rect` shape attribute types are supported. Polygons
    are converted into bboxes that surround the entire shape.

### CODE REVIEW

**Review by lgvaz — CHANGES_REQUESTED** [review]
Really really nice PR, all is perfect!

Only one last thing before we merge (that I forgot to mention previously, sorry), can you add the changes to `CHANGELOG.md`? You can add a line after `##Added` mentioning the addition of this new parser and pointing to this PR.

Thanks a lot for the contribution!

**Comment by jerbly** [comment]
@lgvaz - done!

**Comment by ai-fast-track** [comment]
Thanks a lot @jerbly for the contribution!

**Review by lgvaz — APPROVED** [review]
Perfect!

Thanks a lot for the PR :heart:

**Pull request merged**
