### PR TITLE
Fix coco mask vstack error

### PR DESCRIPTION
**Pull request by aisensiy**
I have an ugly hot fix for this issue https://github.com/airctic/icevision/issues/1094, but I this the solution is not quite numpy. Hope someone can give a better implementation for the code.

### CODE REVIEW

**Comment by fstroth** [comment]
I think you choose the right place in the code to address the problem. Could you change the code to look like this:

```python
def convert_raw_prediction(
    sample,
    raw_pred: dict,
    record: BaseRecord,
    detection_threshold: float,
    keep_image: bool = False,
):
    # convert predictions
    raw_bboxes, raw_masks = raw_pred
    scores, labels, bboxes = _unpack_raw_bboxes(raw_bboxes)

    # When no prediction was made for a class the mask will be empty which creates problems when using np.vstack. So we fill empty predictions with empty masks
    empty_mask = np.full((0, sample["img"].shape[-2], sample["img"].shape[-1]), False)
    filled_raw_masks = [mask if mask != [] else empty_mask for mask in raw_masks]

    keep_mask = scores > detection_threshold
    keep_scores = scores[keep_mask]
    keep_labels = labels[keep_mask]
    keep_bboxes = [BBox.from_xyxy(*o) for o in bboxes[keep_mask]]
    keep_masks = MaskArray(np.vstack(filled_raw_masks)[keep_mask])

    keep_labels = convert_background_from_last_to_zero(
        label_ids=keep_labels, class_map=record.detection.class_map
    )
```
Then we can merge. Thank you for your contribution!

**Comment by aisensiy** [comment]
The ci failed https://github.com/airctic/icevision/runs/6147889052?check_suite_focus=true

And the error message seems the same one described here: https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click

But when I change the black version, it shows another conflict:

image

**Comment by fstroth** [comment]
Strange the correct version of black should be 20.8b1 according to this [line](https://github.com/airctic/icevision/blob/master/setup.cfg#L57). I think you can just force install version 20.8b1 and run black then everything should be fine.

**Comment by aisensiy** [comment]
> Strange the correct version of black should be 20.8b1 according to this [line](https://github.com/airctic/icevision/blob/master/setup.cfg#L57). I think you can just force install version 20.8b1 and run black then everything should be fine.

https://github.com/airctic/icevision/blob/60b5a6db2e86ebc36d91709b92d06cacd5ccab8d/.github/workflows/black.yml#L27

But the CI failed in black format https://github.com/airctic/icevision/runs/6147889052?check_suite_focus=true 

But I still use black to format the code manually.

**Comment by fstroth** [comment]
@ai-fast-track do you have any insight on this CI problem?

**Comment by aisensiy** [comment]
> @ai-fast-track do you have any insight on this CI problem?

I checked the previous action history and this action failed not just at this PR...It seems already got break for serval times.

**Comment by fstroth** [comment]
In that case I think we can ignore the test.

**Review by FraPochetti — APPROVED** [review]

**Comment by fstroth** [comment]
@aisensiy thank you for the contribution.

**Comment by aisensiy** [comment]
I found that right now the prediction part has memory leak...

https://github.com/airctic/icevision/blob/743cb7df0dae7eb1331fc2bb66fc9ca09db496cd/icevision/models/mmdet/common/mask/prediction.py#L105-L152

I use some simple debug method:

```diff
     # When no prediction was made for a class the mask will be empty which creates problems when using np.vstack. So we fill empty predictions with empty masks
-    empty_mask = np.full((0, sample["img"].shape[-2], sample["img"].shape[-1]), False)
-    filled_raw_masks = [mask if mask != [] else empty_mask for mask in raw_masks]
+    # empty_mask = np.full((0, sample["img"].shape[-2], sample["img"].shape[-1]), False)
+    filled_raw_masks = [mask for mask in raw_masks if mask != []]
 
+    usage = Process().memory_info().rss / 1024 / 1024
+    logger.info("memory usage before:\t{}", usage)
     keep_mask = scores > detection_threshold
     keep_scores = scores[keep_mask]
     keep_labels = labels[keep_mask]
     keep_bboxes = [BBox.from_xyxy(*o) for o in bboxes[keep_mask]]
-    keep_masks = MaskArray(np.vstack(filled_raw_masks)[keep_mask])
+    logger.info("shape of keep_mask:        {}", keep_mask.shape)
+    result = np.vstack(filled_raw_masks)[keep_mask]
+    logger.info("shape of keep_mask result: {}", result.shape)
+    keep_masks = MaskArray(result)
 
     keep_labels = convert_background_from_last_to_zero(
         label_ids=keep_labels, class_map=record.detection.class_map
@@ -142,6 +149,9 @@ def convert_raw_prediction(
     pred.detection.set_bboxes(keep_bboxes)
     pred.detection.set_mask_array(keep_masks)
     pred.above_threshold = keep_mask
+    
+    usage = Process().memory_info().rss / 1024 / 1024
+    logger.info("memory usage after:\t{}", usage)
 
     if keep_image:
         image = mmdet_tensor_to_image(sample["img"])
```

And I found the memory usage increase quickly. This is ok if the memory is released after every validation part. But after

https://github.com/airctic/icevision/blob/743cb7df0dae7eb1331fc2bb66fc9ca09db496cd/icevision/metrics/coco_metric/coco_metric.py#L41-L43

The memory report in python is released. However the actually memory usage is still very high. After several epochs the training will run out of memory.

## sampe code

```python
from icevision.all import *

selection = 0

if selection == 0:
    model_type = models.mmdet.mask_rcnn
    backbone = model_type.backbones.resnet50_fpn_1x

if selection == 1:
    model_type = models.mmdet.mask_rcnn
    backbone = model_type.backbones.mask_rcnn_swin_t_p4_w7_fpn_1x_coco

if selection == 2:
    model_type = models.mmdet.yolact
    backbone = model_type.backbones.r101_1x8_coco


# Loading Data
# Create the parser
parser = parsers.COCOMaskParser(
    annotations_filepath="/input0/annotation/train.json",
    img_dir="/input0/train2017",
)

train_rs, valid_rs = parser.parse(RandomSplitter([0.2, 0.8], seed=42))
image_size = 640
train_tfms = tfms.A.Adapter([*tfms.A.resize_and_pad(image_size), tfms.A.Normalize()])
valid_tfms = tfms.A.Adapter([*tfms.A.resize_and_pad(image_size), tfms.A.Normalize()])

train_dl = model_type.train_dl(train_ds, batch_size=4, num_workers=6, shuffle=True)
valid_dl = model_type.valid_dl(valid_ds, batch_size=4, num_workers=6, shuffle=False)

model = model_type.model(backbone=backbone(pretrained=True), num_classes=len(parser.class_map)) 


metrics = [COCOMetric(metric_type=COCOMetricType.mask, print_summary=True)]

class LightModel(model_type.lightning.ModelAdapter):
    def configure_optimizers(self):
        return Adam(self.parameters(), lr=5e-4)
    
light_model = LightModel(model, metrics=metrics)
trainer = pl.Trainer(max_epochs=5, gpus=1)
trainer.fit(light_model, train_dl, valid_dl) # If train without the valid_dl part, there is no memory leak any more.
```

**Pull request merged**
