### PR TITLE
Add PVTv2 backbone to RetinaNet

### PR DESCRIPTION
**Pull request by dnth**
This PR adds [Pyramid Vision Transformer v2](https://arxiv.org/abs/2106.13797) backbone to the RetinaNet model.

Configs and weights from mmdet repo
https://github.com/open-mmlab/mmdetection/tree/master/configs/pvt

### CODE REVIEW

**Comment by ai-fast-track** [comment]
Hey @dnth, 

I just wanted to confirm this PR is aligned with the structure that we design during our call.

I have the impression the answer is Yes. In that case, I can merged it!

**Comment by dnth** [comment]
> Hey @dnth,
> 
> I just wanted to confirm this PR is aligned with the structure that we designed during our call.
> 
> I have the impression the answer is Yes. In that case, I can merged it!

Now it is!

**Comment by dnth** [comment]
COCO Metric for RetinaNet with PVTv2 B3 backbone

retina-pvtb3

**Comment by dnth** [comment]
To use PVT backbone we must update to `mmdet==2.20.0`. However this causes a [problem](https://github.com/airctic/icevision/pull/1041#issuecomment-1019735064) with VFNet models.

**Pull request closed without merging**
