### PR TITLE
Swin Transformer notebook

### PR DESCRIPTION
**Pull request by dnth**
This PR adds a notebook to show users how to use Swin Transformer as backbone for the RetinaNet and VFNet model.

### CODE REVIEW

**Comment by FraPochetti** [comment]
Hey @dnth thanks a lot man!
Would you mind reverting the changes you made to the `getting_started` notebook?
`notebooks/getting_started_object_detection.ipynb`
There are a couple of tweaks that I don't think are needed for this PR, e.g. adding the Swin notebook.

**Comment by FraPochetti** [comment]
Also, feel free to add the Swin notebook to the `Other tutorials` section of the docs, [here](https://github.com/airctic/icevision/blob/master/docs/mkdocs.yml#L57).
It'd be cool to have it there!

**Review by FraPochetti — CHANGES_REQUESTED** [review]
Hey @dnth thanks a lot man!
Would you mind reverting the changes you made to the getting_started notebook?
notebooks/getting_started_object_detection.ipynb
There are a couple of tweaks that I don't think are needed for this PR, e.g. adding the Swin notebook.

Also, feel free to add the Swin notebook to the Other tutorials section of the docs, [here](https://github.com/airctic/icevision/blob/master/docs/mkdocs.yml#L57).
It'd be cool to have it there!

**Comment by dnth** [comment]
I have updated the PR following the suggestions above. Is there anything left out?

**Comment by FraPochetti** [comment]
I don't think so Dickson.
Thanks a lot once again!

**Pull request merged**
