### PR TITLE
Add Dockerfile

### LINKED ISSUE #355: Dockerfile does not build
## 🐛 Bug
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 18.04]

**Additional context**

### PR DESCRIPTION
**Pull request by ydcjeff**
Add and build dockerfile
Fixes #355

### CODE REVIEW

**Comment by ydcjeff** [comment]
@lgvaz 
seems like we can't build two envs in github actions, disk is running out of space.
https://github.com/airctic/icevision/pull/508/checks?check_run_id=1307947089
Two separate docker builds would be an option here.

**Comment by lgvaz** [comment]
Very very nice!!! 

Thanks for the very fast PR! I'll check it today at night =)

**Comment by ydcjeff** [comment]
Will you push to docker hub?

**Comment by ai-fast-track** [comment]
Hi @ydcjeff, thanks for your 2 PRs!

I checked the `docker/build-push-action@v2` and it seems that we have to either:
* create both `secrets.DOCKERHUB_USERNAME` and `secrets.DOCKERHUB_TOKEN`, and then no need to provide those keys 
* or, provide other ones (e.g `secrets.MYTOKEN`) by adding the following code: 
`secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}`

Is it correct?

Also, building the Docker image seems to be triggered by a push to master. We will discuss about that option and the another option triggered by a PyPi release. @lgvaz, your thoughts? 

Since we are continually adding new features, it might be more appropriate to use the Push to master as a trigger.

**Comment by ydcjeff** [comment]
Yes, push to docker hub has to use github secrets.
So you want to push to docker hub
- when it's a release
- a commit push to master?

**Comment by lgvaz** [comment]
I think it's a better idea to push to hub only on releases, before we had that strategy of pushing to a branch docker_deploy, but I don't think that is really necessary?

**Comment by ydcjeff** [comment]
It doesn't require to push to deploy_docker branch.
Now, it will be push on release.
it will trigger docker build with push and pull request to master

What left is just adding docker username and repo, feel free to edit to match with yours.

**Comment by ydcjeff** [comment]
@lgvaz any updates?

**Comment by lgvaz** [comment]
@ai-fast-track was the one experimenting with docker, I'll contact him :smiley:

**Comment by ai-fast-track** [comment]
@ydcjeff sorry for the delay. I have been testing Docker on my end, and we have some new ideas that can be integrate with your proposal. I also have some questions about your Docker file. 

Here is my first attempt using the official pytorch docker image as well as offering a `prod` and `dev` option. Mind you this is just a test and not the final thought (the tags don't reflect the final naming):

```
FROM pytorch/pytorch

ARG BUILD=dev

RUN apt-get update && apt-get install -y software-properties-common rsync
RUN add-apt-repository -y ppa:git-core/ppa && apt-get update && apt-get install -y git libglib2.0-dev graphviz && apt-get update


RUN git clone https://github.com/airctic/icevision --depth 1  && git clone https://github.com/airctic/icedata --depth 1
RUN /bin/bash -c "if [[ $BUILD == 'prod' ]] ; then echo \"Production Build\" && cd icevision && pip install \".[all]\"; fi"
RUN /bin/bash -c "if [[ $BUILD == 'dev' ]] ; then echo \"Development Build\" && cd icedata && pip install -e \".[all, dev]\" ; fi"
RUN echo '#!/bin/bash\njupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser' >> run_jupyter.sh

RUN chmod u+x run_jupyter.sh


# To build local image with `dev` tag
# docker build -f Dockerfile -t icevision:dev .

# To run the `dev` docker container and open Jupyter
# docker run -p 8888:8888 icevision:dev ./run_jupyter.sh

# To run docker and open bash
# docker run -it icevision:dev bash
```

We also would like to automate the creation of several IceVision (dev, prod, etc.) and automatically tag by release version (or master) by reading the version tag from the `setup.cfg`. 

If you are comfortable with live-chatting about all this stuff, we can can jump on a call with @lgvaz and finalize this PR at the beginning of week.

**Comment by ydcjeff** [comment]
@ai-fast-track I have added your suggestions, currently testing docker build on PR.
Would you like to build `dev` only option on PR and master and only `prod` when releasing?

**Pull request closed without merging**
