### PR TITLE
Implement show_batch for unet

### PR DESCRIPTION
**Pull request by dnth**
This PR implements `show_batch` for `icevision.models.fastai.unet`.

Screenshot
image

Colab notebook
https://colab.research.google.com/gist/dnth/88a76edb18ece126c36741ff0882c787/getting_started_semantic_segmentation.ipynb

Closes https://github.com/airctic/icevision/issues/1068

### CODE REVIEW

**Comment by ai-fast-track** [comment]
Thanks @dnth. That's a good idea!

**Comment by FraPochetti** [comment]
Thanks a lot @dnth .
Are we ready to merge?

**Comment by dnth** [comment]
Yup! I'm good if there are no changes needed.

**Comment by FraPochetti** [comment]
Merged!
Thanks a ton Dickson!

**Pull request merged**
