### PR TITLE
Fixes typo in Albumentations helper

### LINKED ISSUE #1090: Typo lightning -> lighting in Albumentations helper
There are several instances in the codebase with the typo `lightning` when the intended term is `lighting`

https://github.com/airctic/icevision/blob/af0693e355423e9879c97ab903f324db080411f4/icevision/tfms/albumentations/albumentations_helpers.py#L35

https://github.com/airctic/icevision/blob/af0693e355423e9879c97ab903f324db080411f4/icevision/tfms/albumentations/albumentations_helpers.py#L57

https://github.com/airctic/icevision/blob/af0693e355423e9879c97ab903f324db080411f4/icevision/tfms/albumentations/albumentations_helpers.py#L74

### PR DESCRIPTION
**Pull request by Behnam-H**
Replaced "lightning" with "lighting".

Fixes #1090

### CODE REVIEW

**Comment by FraPochetti** [comment]
Thanks so much for the contribution!
Did you run `black` on the codebase? Check formatting seems to fail.

**Comment by Behnam-H** [comment]
My pleasure :+1: 
It seems to be an [issue](https://github.com/psf/black/issues/2964) with black dependencies.
Its solution seems to be updating `black` version or using `click==8.0.4` for the hook.

**Review by FraPochetti — APPROVED** [review]

**Comment by FraPochetti** [comment]
Awesome. Do you want to add anything to the PR or can we merge?

**Comment by Behnam-H** [comment]
Can I add the necessary dependencies to resolve the "Check Format" issue, or maybe create another PR for that?

**Comment by FraPochetti** [comment]
Thanks so much!

**Pull request merged**
