### PR TITLE
Issue 457: add required update to the jsonschema package to the installation instructions

### LINKED ISSUE #457: Error installing from github on colab
## 📓 Documentation Update
As described in #422 installing from github on colab raises an error because of an outdated package (jsonchema), so the following is necessary before installing on colab:
```
pip install jsonschema --upgrade
```

We have to add this info on `Install.md`

### PR DESCRIPTION
**Pull request by buckley-w-david**
fixes #457

### CODE REVIEW

**Review by lgvaz — APPROVED** [review]
All good!

Congrats @buckley-w-david on your first merged pull request in this project! 🎊

image

Thank you for contributing, and welcome to the IceVision community! 🎉

**Comment by aadhav-n1** [comment]
Not OP, but I think you tagged the wrong person in your reply. CC: @lgvaz 

> All good!
> 
> Congrats @singhalpranav22 on your first merged pull request in this project! confetti_ball
> 
> image
> 
> Thank you for contributing, and welcome to the IceVision community! tada

**Comment by buckley-w-david** [comment]
It's alright, since I was a young lad I've always wanted to be singhalpranav22, this is a chance to live my dream

**Comment by lgvaz** [comment]
hehe, sry 😆

**Comment by lgvaz** [comment]
> I've always wanted to be singhalpranav22, this is a chance to live my dream

@buckley-w-david He's a cool dude, I can see why that can be a dream =)

Hahaha cutting the BS, sorry for that, it's an automated template we're curating for new contributors and I forgot to change the name

**Comment by lgvaz** [comment]
And I just realized I've done this in other PRs as well, @singhalpranav22 will be getting a lot of mentions hahahahahah

**Pull request merged**
