### PR TITLE
monkey-patching wandb.watch when training a fastai RCNN learner with …

### PR DESCRIPTION
**Pull request by FraPochetti**
…the WandbCallback

This one addresses issue #490

### CODE REVIEW

**Review by lgvaz — COMMENTED** [review]
Looks good! Just a question before we merge this, if instead of patching we use `log=None`, is the bug solved?

**Comment by FraPochetti** [comment]
> if instead of patching we use log=None, is the bug solved?

Nope. That just doesn't log the gradients.

**Comment by lgvaz** [comment]
Okay, makes a lot of sense!!

So, the final thing before we merge, can you add a `logger.warning` if `if len(is_wandb) == 1:`?

It would be nice to open a new issue in icevision to show your findings, you can just copy and paste the messages you sent me on discord, explaining that torchvision rcnn models are having a problem with the wandb hooks and the best quick solution we found is to simply don't add the hooks

Then in the warning message you could say something like "Wandb quickfix implemented, for more info check issue #number_of_issue"

**Comment by FraPochetti** [comment]
Sure will do!
Shall I just document my findings [here](https://github.com/airctic/icevision/issues/490) or create a new issue from scratch?

**Comment by FraPochetti** [comment]
I added a final comment to [this](https://github.com/airctic/icevision/issues/490) issue describing what we did.
Is this a sufficient level of detail?

**Comment by lgvaz** [comment]
The level of detail is perfect!

Open another issue because the original one contains useless information and will be closed by this PR. It's easier to have a direct and clear issue for further reference =)

**Comment by FraPochetti** [comment]
Done.
[Issue](https://github.com/airctic/icevision/issues/527) created and PR updated.

**Review by lgvaz — APPROVED** [review]
Looks perfect! Thanks SO MUCH again Francesco, as I said before, the amount of line changes doesn't reflect at all the work put into this :heart:

**Pull request merged**
