### PR TITLE
Update Dataset to pass the model's class map to show_preds and display the string labels in the prediction results

### PR DESCRIPTION
**Pull request by elmourr**
This enables passing the model's class labels to an image dataset when invoking:  dataset.from_images 
and to display the labels along with the BBoxes when running inference with show_pred.
Method:  
infer_neg_ds = Dataset.from_images([img], tfms, class_map=class_map)
show_preds(preds=preds[:6], class_map = class_map,denormalize_fn=denormalize_imagenet,ncols=3,)

### CODE REVIEW

**Comment by FraPochetti** [comment]
Thanks for the PR!

**Comment by elmourr** [comment]
> Thanks for the PR!

not at all, i's been great!

**Review by lgvaz — COMMENTED** [review]
Hii! Thanks a lot for the PR

I'm not sure we can go ahead with this (maybe as a quickfix?), the issue it's not safe to assume that our record will contain the `detection` task, you can be doing classification for example.

Hmm... Maybe because the library is mainly about the detection now this would be an okay assumption to make

**Comment by FraPochetti** [comment]
> Hmm... Maybe because the library is mainly about the detection now this would be an okay assumption to make
I think it could be ok as a quickfix, yes.

**Comment by lgvaz** [comment]
@elmourr hey, we can merge this one, but I believe you will need to open a new PR to merge into master like I explained in the other one

**Pull request closed without merging**
