### PR TITLE
Properly restore transformed masks after unload

### LINKED ISSUE #978: transforms modify mask_array, but masks and mask_parts remain unchanged
## 🐛 Bug
**Describe the bug**
When transforms are applied to a record (`icevision.Dataset.__getitem__`), the resulting `record.detection` has `mask_array` updated by the transform. But the `masks` and `mask_parts` attributes (in `InstanceMasksRecordComponent`) still have `points` values that represent the original record.

This results in problems later on when the codebase attempts to re-create `mask_array` from the `masks` component which has not been transformed with the image (for example, in `convert_record_to_coco_style`, which causes `COCOMetric` to report incorrect results on resized data whenever the mask_array has to be recreated).

**To Reproduce**
1. Retrieve a single record from an `icevision.Dataset` with a resizing transform.
2. call `MaskArray.from_masks(record.detection.masks, record.height, record.width)` and compare the result with `record.detection.mask_array`
3. Note the mask_array is significantly different when recreated from the `record.detection.masks`
The following notebook snippet demonstrates:
```
import icevision
from icevision.all import *
import numpy as np

annotations_path = '/path-to-coco-dataset/coco2017/val/annotations/instances_val2017.json'
images_path = '/path-to-coco-dataset/coco2017/val/val2017'
# Loading Data
class_map = icedata.coco.class_map()

# Randomly split our data into train/valid
data_splitter = RandomSplitter([0.8, 0.2])

# COCO parser: provided out-of-the-box
parser = icevision.parsers.COCOMaskParser(
    annotations_filepath=annotations_path, 
    img_dir=images_path)
train_records, valid_records = parser.parse(data_splitter)
train_ds = icevision.Dataset(train_records, tfms.A.Adapter([
            tfms.A.HorizontalFlip(),
            *tfms.A.resize_and_pad(size=[1280,720])]))

record = train_ds[0]
mask_array = MaskArray.from_masks(record.detection.masks, record.height, record.width)

assert record.detection.img.shape == (720, 1280, 3)
assert record.detection.mask_array.shape == mask_array.shape

def show_masks(mask_array, cmap='gray'):
    w = 10
    h = 10
    fig = plt.figure(figsize=(20, 16))
    columns = 4
    rows = int(math.ceil(len(mask_array) / columns))
    for i in range(1, columns*rows +1):
        if i >= len(mask_array):
            break
        fig.add_subplot(rows, columns, i)
        plt.imshow(mask_array[i], cmap=cmap)
    plt.show()

show_masks(mask_array.data, cmap='hot')
show_masks(record.detection.mask_array.data, cmap='cool')
```
image
(note the flip and resize have been lost)

**Expected behavior**
The `record.detection.masks` and `record.detection.mask_parts` should be reacreated from `record.detection.mask_array` after the transforms are applied.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 18.04]

**Additional context**
icevision 0.11

### PR DESCRIPTION
**Pull request by matt-deboer**
Stores the results of applying transforms to the `detection.masks` of a record, which allows the `mask_array` to be properly reconstructed later (after `.unload()` has been called on the record).

Fixes #978.

### CODE REVIEW

**Comment by ai-fast-track** [comment]
Thank you for your contribution @matt-deboer! We really appreciate that.

@fstroth is reviewing your PR

**Comment by fstroth** [comment]
I created a PR to the fix_978 branch with two fixes that result from the changes. With those merged this PR should be good to go (@ai-fast-track).
Again thanks a lot for the contribution @matt-deboer .

**Comment by matt-deboer** [comment]
@fstroth, it looks like your PR to my PR causes the codecov test to fail (it was previously passing, IIRC)...how do you want to proceed?

**Comment by ai-fast-track** [comment]
Thanks a lot @matt-deboer for contributing. Apologies for the delay


Thanks @fstroth for reviewing the PR.

**Pull request merged**
