### PR TITLE
First try at saving/loading records from pickle

### PR DESCRIPTION
**Pull request by FraPochetti**
So, I added `get_root_dir` to `data_dir.py` but tests are failing because they cannot find the function.
Am I screwing something up with the imports?

```
FAILED parsers/test_coco_parser.py::test_bbox_parser - NameError: name 'get_root_dir' is not defined
FAILED parsers/test_coco_parser.py::test_mask_parser - NameError: name 'get_root_dir' is not defined
FAILED parsers/test_parser.py::test_parser - NameError: name 'get_root_dir' is not defined
FAILED parsers/test_voc_parsers.py::test_voc_annotation_parser - NameError: name 'get_root_dir' is not defined
FAILED parsers/test_voc_parsers.py::test_voc_mask_parser - NameError: name 'get_root_dir' is not defined
```

### CODE REVIEW

**Review by lgvaz — CHANGES_REQUESTED** [review]
The implementation looks great! Exactly what we discussed in the issue!

One test is failing because a parser is being used twice and the cache is being loaded while the data changed, all we have to do is pass `use_cached=False` to it. You can fix that if you want or I can fix it before mergining.

Just one more request before we merge this, can you write a simple test checking the pickle file was saved correctly? I understand creating tests can be hard at first but I'll help with everything I can.

Go to `tests/parsers/test_parser.py` and you will find the function `test_parser`, at the end of the asserts add a new check to verify the pickle file exists. Additionaly you can load the pickle file and assert it has the same contents as `records`

**Comment by FraPochetti** [comment]
> One test is failing because a parser is being used twice and the cache is being loaded while the data changed

I wanted to check which one you were referring to as all tests were passing for me locally (I mean `pytest parsers`), and something super awkward happened.
I re-run `pytest parsers` and go the following

```
FAILED parsers/test_coco_parser.py::test_bbox_parser - AttributeError: Can't get attribute 'RecordBaseRecordImageidRecordMixinFilepathRecordMixinSizeRecordMixinLabelsRecordMixinAreasRecordMixinIsCrowdsRecordMixinBBoxesRecordMixinRecordMixinMutableMappingMappingCollectionSizedIterableContainerobject' on <module '...
FAILED parsers/test_coco_parser.py::test_mask_parser - AttributeError: Can't get attribute 'RecordBaseRecordImageidRecordMixinFilepathRecordMixinSizeRecordMixinLabelsRecordMixinAreasRecordMixinIsCrowdsRecordMixinBBoxesRecordMixinMasksRecordMixinRecordMixinMutableMappingMappingCollectionSizedIterableContainerobje...
FAILED parsers/test_parser.py::test_parser - AttributeError: Can't get attribute 'RecordBaseRecordImageidRecordMixinSizeRecordMixinFilepathRecordMixinLabelsRecordMixinBBoxesRecordMixinRecordMixinMutableMappingMappingCollectionSizedIterableContainerobject' on <module '__main__' from '/home/fra/miniconda3/envs/ice...
FAILED parsers/test_voc_parsers.py::test_voc_annotation_parser - AttributeError: Can't get attribute 'RecordBaseRecordImageidRecordMixinFilepathRecordMixinSizeRecordMixinLabelsRecordMixinBBoxesRecordMixinRecordMixinMutableMappingMappingCollectionSizedIterableContainerobject' on <module '__main__' from '/home/fra...
FAILED parsers/test_voc_parsers.py::test_voc_mask_parser - AttributeError: Can't get attribute 'RecordBaseRecordImageidRecordMixinFilepathRecordMixinSizeRecordMixinLabelsRecordMixinBBoxesRecordMixinMasksRecordMixinRecordMixinMutableMappingMappingCollectionSizedIterableContainerobject' on <module '__main__' from ...
```

Is this what you are referring to?

**Comment by lgvaz** [comment]
> Is this what you are referring to?

hahahah that was not the one, for some reason that is not happening on the CI, you can check the full run [here](https://github.com/airctic/icevision/pull/504/checks?check_run_id=1301515350)

```python
__________________________ test_voc_annotation_parser __________________________

samples_source = Path('/home/runner/work/icevision/icevision/samples')
voc_class_map = <ClassMap: {'background': 0, 'aeroplane': 1, 'bicycle': 2, 'bird': 3, 'boat': 4, 'bottle': 5, 'bus': 6, 'car': 7, 'cat... 'horse': 13, 'motorbike': 14, 'person': 15, 'pottedplant': 16, 'sheep': 17, 'sofa': 18, 'train': 19, 'tvmonitor': 20}>

    def test_voc_annotation_parser(samples_source, voc_class_map):
        annotation_parser = parsers.voc(
            annotations_dir=samples_source / "voc/Annotations",
            images_dir=samples_source / "voc/JPEGImages",
            class_map=voc_class_map,
        )
        records = annotation_parser.parse(data_splitter=SingleSplitSplitter())[0]
    
>       assert len(records) == 2
E       assert 4 == 2
E        +  where 4 = len([Record:\n	- Image ID: 0\n	- Filepath: /home/runner/work/icevision/icevision/samples/fridge/odFridgeObjects/images/10.jp...s: [2, 4]\n	- BBoxes: [<BBox (xmin:56, ymin:148, xmax:209, ymax:514)>, <BBox (xmin:328, ymin:180, xmax:449, ymax:502)>]])

tests/parsers/test_voc_parsers.py:12: AssertionError
```

**Comment by FraPochetti** [comment]
Interesting! :D let me look into this. I might have declared victory too soon.

**Comment by FraPochetti** [comment]
Ok, so the awkward errors I refer to, occur when I run `pytest parsers` the second time, not the first (which I why I did not catch them in the first place). So, clearly, given `use_cached=True`, the pickle it is loading back is not what it expects to be.

**Comment by FraPochetti** [comment]
I am still trying to figure out what the heck this means `RecordBaseRecordImageidRecordMixinSizeRecordMixinFilepathRecordMixinLabelsRecordMixinBBoxesRecordMixinRecordMixinMutableMappingMappingCollectionSizedIterableContainerobject`

In the meantime, getting back to what you commented

> One test is failing because a parser is being used twice and the cache is being loaded while the data changed

Are you referring to `test_voc_annotation_parser`? 
`parsers.voc` is indeed invoked twice, the first time within `test_voc_annotation_parser`, the second within `test_voc_mask_parser`. 
It seems the first is failing, not the second.

Also, when I run `pytest parsers` on my local machine everything looks good (the second time I get the above awkward error).
Are CI tests somehow different?
image

**Comment by FraPochetti** [comment]
Btw, the screenshot above is already after adding the 2 asserts you requested to test_parsers 😉

**Comment by FraPochetti** [comment]
So, I think I found the culprit but I am still having a hard time figuring this out.
First, let me explain how we got here and how this issue fell through the cracks:

1. **First mistake**: I run my experiments in Colab. Everything worked well there, but obviously, to get it to work I had to hack some source files, so eventually, I lost some critical interdependencies across modules. I thought all was good but just because everything was defined *in* the notebook (one unique file).
2. **Second mistake**: Once done with Colab, I copy-pasted the new `parser.parse` function in VSCode, in my local env. I then run `pytest parsers`. All tests passed. I run those once, though. In this first pass, all pickle files got created as expected. I should have run a second time to check whether _loading_ back worked too (given `use_cached=True`). I did not. If I had done so I would have stumbled upon the following (this is one example; all tests fail in the same way):

```
AttributeError: Can't get attribute 'RecordBaseRecordImageidRecordMixinSizeRecordMixinFilepathRecordMixinLabelsRecordMixinBBoxesRecordMixinRecordMixinMutableMappingMappingCollectionSizedIterableContainerobject' on <module '__main__' from '/home/fra/miniconda3/envs/icevision/bin/pytest'>
```

This monster is driven by [this](https://stackoverflow.com/questions/27732354/unable-to-load-files-using-pickle-and-multiple-modules) annoying pickle issue, which, tbh, I am not even sure I completely get.
I tried to implement a couple of proposed solutions, with no luck.
Keep you posted.

**Comment by FraPochetti** [comment]
I have played around with this quite a bit without much luck.
The issue is described [here](https://stackoverflow.com/questions/40287657/load-pickled-object-in-different-file-attribute-error/40288996) and [here](https://www.reddit.com/r/learnpython/comments/e0c05h/pickle_attributeerror_cant_get_attribute_myclass/) and it basically boils down to `loading a pickled file in a module that is different from the module where I pickled the file.`
Do you have any suggestions?

**Comment by FraPochetti** [comment]
Maybe we can bring this to the attention of the community in Discord?

**Comment by lgvaz** [comment]
> I am still trying to figure out what the heck this means `RecordBaseRecordImageidRecordMixinSizeRecordMixinFilepathRecordMixinLabelsRecordMixinBBoxesRecordMixinRecordMixinMutableMappingMappingCollectionSizedIterableContainerobject`

Oh, I can help you with that! This was a new addition and still has to be documented, it's a hack for making a local object pickable. It would be easier to explain it in a call, are you available at any time in the next week? 

> This monster is driven by this annoying pickle issue, which, tbh, I am not even sure I completely get.

Hah! Pickle it's then!!! Okay okay, I have some ideas, the easiest and less stresfull solution would be for us to jump into a call and take a look at this, as I said in the previous comment I can explain **why** we are doing this and what is the best way of handling what is happening.

I think this is the only place on the library where some python black magic is happening, and it was just added last week (with the autofix) so it's still not documented, I was not expecting that this issue would stumble into that, sry =x

**Comment by FraPochetti** [comment]
Sure, let's do this!
Super eager to learn something new :D
I am available anyday next week, almost anytime.
We are 4 hours apart (myself in CET, yourself in GMT-3).
Just pick a slot and we can arrange something.

**Comment by FraPochetti** [comment]
And no need to be sorry man!

**Comment by lgvaz** [comment]
> I am available anyday next week, almost anytime.

Nice! I'll message you on Discord tomorrow and we can find a common time =)

**Comment by FraPochetti** [comment]
image

**Comment by FraPochetti** [comment]
Ok... this does not happen to me locally
image

Locally, I am running tests twice to force pickle reloading

**Comment by FraPochetti** [comment]
I think I found the issue.
Keep you posted.

**Comment by FraPochetti** [comment]
image

**Review by lgvaz — CHANGES_REQUESTED** [review]
Alright! This issue was way harder than I originally expected but after a lot of figuring it out I think we reached a very good solution!

The final requested change is just to use a temporary path to save the pickle file so it automatically gets deleted after the testing session is over. You can find more info about it [here](https://docs.pytest.org/en/stable/tmpdir.html#the-tmpdir-fixture).

**Review by lgvaz — APPROVED** [review]

**Comment by lgvaz** [comment]
Alright, perfect!! Here we go Francesco!

Thanks a lot again ^^

**Pull request merged**
